name: '11ty builder'
description: 'action to build a 11ty website and publish it to Github Pages'
author: 'Katherine Burgess, Douglas Luman'

inputs:
  directory:
    description: 'A directory that contains your 11ty website'
    default: 'site'
    required: true
    type: string

permissions:
  contents: read
  pages: write
  id-token: write

runs:
  using: 'composite'
  steps:
    - run: |
        cd ${{ inputs.directory }}
        npm install
        npm run build
      shell: bash
