name: '11ty builder'
description: 'action to build a 11ty website and publish it to Github Pages'
author: 'Katherine Burgess, Douglas Luman'

inputs:
  directory:
    description: 'A directory that contains your 11ty website'
    default: 'site'
    required: true
    type: string

permissions:
  contents: read
  pages: write
  id-token: write

runs:
  using: 'composite'
  steps:
    - run: Checkout
      uses: actions/checkout@v3
    - run: Setup Pages
      uses: actions/configure-pages@v2
    - run: Build the website
      shell: |
        cd ${{ inputs.directory }}
        npm install
        npm run build
    - run: Upload artifact
      uses: actions/upload-pages-artifact@v1.0.4
      with:
        name: ${{ inputs.directory }}
        path: ./${{ inputs.directory }}/_site
