name: '11ty builder'
description: 'action to build a 11ty website and publish it to Github Pages'
author: 'Katherine Burgess, Douglas Luman'
on:
  workflow_dispatch:
    inputs:
      directory:
        description: 'A directory that contains your 11ty website'
        default: 'site'
        required: true
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Build the website
        with:
          directory: ${{ inputs.directory }}
        run: |
          cd ${{ inputs.directory }}
          npm install
          npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          name: ${{ inputs.directory.name }}
          path: ./${{ inputs.directory.name }}/_site
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
